# Let's clean up here
## 02. Collecting and cleaning data
Typically, we will initially receive a file containing more or less structured data and a task to be solved. It is rarely prepared for solving our particular issue - most of the times it is just a raw output of some kind of application or the database exported to CSV, JSON or so. 

Sometimes gathering the data is a part of the job, however we will assume we have already got the file with the data extracted from the system that it comes from.

### Example 01. Lyrics from Metrolyrics
As a first example we are going to take a dataset consisting of 380 000 lyrics of songs. It is available as a CSV file. Let have a look at what is inside.

In [5]:
import pandas as pd
import pandas_profiling

# Load the CSV file
lyrics_df = pd.read_csv("./datasets/380000-lyrics-from-metrolyrics/lyrics.csv.zip", 
                        compression="zip")
# Show a table with the first 10 entries
lyrics_df.head(n=10)

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>index</th>
      <th>song</th>
      <th>year</th>
      <th>artist</th>
      <th>genre</th>
      <th>lyrics</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>ego-remix</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>Oh baby, how you doing?\nYou know I'm gonna cu...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>then-tell-me</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>playin' everything so easy,\nit's like you see...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>honesty</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>If you search\nFor tenderness\nIt isn't hard t...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>you-are-my-rock</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>Oh oh oh I, oh oh oh I\n[Verse 1:]\nIf I wrote...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
      <td>black-culture</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>Party the people, the people the party it's po...</td>
    </tr>
    <tr>
      <th>5</th>
      <td>5</td>
      <td>all-i-could-do-was-cry</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>I heard\nChurch bells ringing\nI heard\nA choi...</td>
    </tr>
    <tr>
      <th>6</th>
      <td>6</td>
      <td>once-in-a-lifetime</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>This is just another day that I would spend\nW...</td>
    </tr>
    <tr>
      <th>7</th>
      <td>7</td>
      <td>waiting</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>Waiting, waiting, waiting, waiting\nWaiting, w...</td>
    </tr>
    <tr>
      <th>8</th>
      <td>8</td>
      <td>slow-love</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>[Verse 1:]\nI read all of the magazines\nwhile...</td>
    </tr>
    <tr>
      <th>9</th>
      <td>9</td>
      <td>why-don-t-you-love-me</td>
      <td>2009</td>
      <td>beyonce-knowles</td>
      <td>Pop</td>
      <td>N-n-now, honey\nYou better sit down and look a...</td>
    </tr>
  </tbody>
</table>
</div>

As we may see, the file contains 6 columns: index, song title, release year, artist, genre and lyrics. Let try to have a brief overview of what is really inside. We need to have some kind of intuition about the data, in order to be able to work with it more.

First of all, let try to find all the years that the songs come from.

In [5]:
print(lyrics_df["year"].unique())

[2009 2007 2013 2010 2012 2006 2016 2011 2015 2008 2014 1998 2002 1995 2004
 1972 2005 1978 1970 1981 1994 1997 2003 1976 2001 1983 1987 1993 1982 1986
 1992 1984 1977 1989 1979 1996 1988 1974 1975 1973 1971 1999 1990 1991 1985
 2000 1980  702  112 2038 1968   67]


At the first look we may see there might be a data issue, or we have quite old songs in a database (67, 112, 702). What's more, we have at least one example of the song coming from a future: year 2038 also appears on our list. Let have a look at these examples more in details.

In [6]:
# Filter the dataframe to get only the rows which have the "year" property set to 67, 112, 702 or 2038
old_lyrics_df = lyrics_df.loc[lyrics_df["year"].isin([67, 112, 702, 2038])]
old_lyrics_df.head(16)

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>index</th>
      <th>song</th>
      <th>year</th>
      <th>artist</th>
      <th>genre</th>
      <th>lyrics</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>27657</th>
      <td>27657</td>
      <td>star</td>
      <td>702</td>
      <td>clipse</td>
      <td>Hip-Hop</td>
      <td>You're my star\nIt's such a wonder how you shi...</td>
    </tr>
    <tr>
      <th>69708</th>
      <td>69708</td>
      <td>anywhere-remix</td>
      <td>112</td>
      <td>dru-hill</td>
      <td>Hip-Hop</td>
      <td>Here we are all alone\nYou and me, privacy\nAn...</td>
    </tr>
    <tr>
      <th>112159</th>
      <td>112159</td>
      <td>atchim</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112160</th>
      <td>112160</td>
      <td>o-areias</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112161</th>
      <td>112161</td>
      <td>era-uma-vez-um-cavalo</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112162</th>
      <td>112162</td>
      <td>anita</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112163</th>
      <td>112163</td>
      <td>todos-os-patinhos</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112164</th>
      <td>112164</td>
      <td>joana-come-a-papa</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112165</th>
      <td>112165</td>
      <td>atirei-o-pau-ao-gato</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112166</th>
      <td>112166</td>
      <td>eu-vi-um-sapo</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112167</th>
      <td>112167</td>
      <td>pipi-das-meias-altas</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112168</th>
      <td>112168</td>
      <td>minhoca</td>
      <td>2038</td>
      <td>anita</td>
      <td>Rock</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>147914</th>
      <td>147914</td>
      <td>it-s-over-now-remix</td>
      <td>112</td>
      <td>g-dep</td>
      <td>Hip-Hop</td>
      <td>What is this?\nNumbers in your pocket\nI remem...</td>
    </tr>
    <tr>
      <th>238541</th>
      <td>238541</td>
      <td>come-see-me-remix</td>
      <td>112</td>
      <td>black-rob</td>
      <td>Hip-Hop</td>
      <td>Baby, you can come see me 'cause I need you he...</td>
    </tr>
    <tr>
      <th>315540</th>
      <td>315540</td>
      <td>let-s-lurk</td>
      <td>67</td>
      <td>giggs</td>
      <td>Hip-Hop</td>
      <td>Verse 1:\nStill pulling up on smoke\nSkeng in ...</td>
    </tr>
    <tr>
      <th>335205</th>
      <td>335205</td>
      <td>i-can-t-believe</td>
      <td>112</td>
      <td>faith-evans</td>
      <td>Pop</td>
      <td>[Chorus]\nI can't believe that love has gone a...</td>
    </tr>
  </tbody>
</table>
</div>

There are several possibilites if we face such an issue. The first one is to just leave the values as they are and to assume we received correct data. That is the simplest, and probably the worst approach. The second one would be to correct the entries using some external knowledge, but in some of the cases it won't be possible, as the data is unique and impossible to be reproduced. Another possibility is to correct the values with a mean, or any other value that might be calculated using the rest of the data we have. Neverthless, we'll just remove this entries to not impact our further results.

In [8]:
lyrics_df = lyrics_df[lyrics_df["year"] > 702]
lyrics_df = lyrics_df[lyrics_df["year"] < 2038]
%store lyrics_df

Stored 'lyrics_df' (DataFrame)


It might be also interesting to see how many songs come from each year. For that we can simply generate a chart that will show it in an easy to understand manner.

In [9]:
# Calculate number of entries for each unique year and display a chart
counted_by_year = lyrics_df.groupby("year").count()
counted_by_year["index"].plot()

#### Automating the process
We probably should perform the same process again for every column of our file. Due to the fact it is a common problem for all the people working with data, we may try to automate the process, just in order to have an overview of all the data available. We will leave two columns (song and lyrics) for now, as they will be used a lot in the next steps, we will perform. The next example shows how to do such analysis almost effortlessly.

In [6]:
pandas_profiling.ProfileReport(lyrics_df[["year", "artist", "genre"]])

<meta charset="UTF-8">

<style>

        .variablerow {
            border: 1px solid #e1e1e8;
            border-top: hidden;
            padding-top: 2em;
            padding-bottom: 2em;
            padding-left: 1em;
            padding-right: 1em;
        }

        .headerrow {
            border: 1px solid #e1e1e8;
            background-color: #f5f5f5;
            padding: 2em;
        }
        .namecol {
            margin-top: -1em;
            overflow-x: auto;
        }

        .dl-horizontal dt {
            text-align: left;
            padding-right: 1em;
            white-space: normal;
        }

        .dl-horizontal dd {
            margin-left: 0;
        }

        .ignore {
            opacity: 0.4;
        }

        .container.pandas-profiling {
            max-width:975px;
        }

        .col-md-12 {
            padding-left: 2em;
        }

        .indent {
            margin-left: 1em;
        }

        /* Table example_values */
            table.example_values {
                border: 0;
            }

            .example_values th {
                border: 0;
                padding: 0 ;
                color: #555;
                font-weight: 600;
            }

            .example_values tr, .example_values td{
                border: 0;
                padding: 0;
                color: #555;
            }

        /* STATS */
            table.stats {
                border: 0;
            }

            .stats th {
                border: 0;
                padding: 0 2em 0 0;
                color: #555;
                font-weight: 600;
            }

            .stats tr {
                border: 0;
            }

            .stats tr:hover{
                text-decoration: underline;
            }

            .stats td{
                color: #555;
                padding: 1px;
                border: 0;
            }


        /* Sample table */
            table.sample {
                border: 0;
                margin-bottom: 2em;
                margin-left:1em;
            }
            .sample tr {
                border:0;
            }
            .sample td, .sample th{
                padding: 0.5em;
                white-space: nowrap;
                border: none;

            }

            .sample thead {
                border-top: 0;
                border-bottom: 2px solid #ddd;
            }

            .sample td {
                width:100%;
            }


        /* There is no good solution available to make the divs equal height and then center ... */
            .histogram {
                margin-top: 3em;
            }
        /* Freq table */

            table.freq {
                margin-bottom: 2em;
                border: 0;
            }
            table.freq th, table.freq tr, table.freq td {
                border: 0;
                padding: 0;
            }

            .freq thead {
                font-weight: 600;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;

            }

            td.fillremaining{
                width:auto;
                max-width: none;
            }

            td.number, th.number {
                text-align:right ;
            }

        /* Freq mini */
            .freq.mini td{
                width: 50%;
                padding: 1px;
                font-size: 12px;

            }
            table.freq.mini {
                 width:100%;
            }
            .freq.mini th {
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                max-width: 5em;
                font-weight: 400;
                text-align:right;
                padding-right: 0.5em;
            }

            .missing {
                color: #a94442;
            }
            .alert, .alert > th, .alert > td {
                color: #a94442;
            }


        /* Bars in tables */
